//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPUSimulator.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InstructionsDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InstructionsDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CPUSimulator.UI.Resources.InstructionsDescriptions", typeof(InstructionsDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calculates (Rxx + Ryy) MOD 2^32 and stores the result in Rxx.
        /// </summary>
        internal static string ADD_Description {
            get {
                return ResourceManager.GetString("ADD_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD RXX,RYY.
        /// </summary>
        internal static string ADD_Label {
            get {
                return ResourceManager.GetString("ADD_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decrements Rxx by one. Decrementing 0 causes an overflow and results in 2^32 -1.
        /// </summary>
        internal static string DEC_Description {
            get {
                return ResourceManager.GetString("DEC_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEC RXX.
        /// </summary>
        internal static string DEC_Label {
            get {
                return ResourceManager.GetString("DEC_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to increments Rxx by one. Incrementing 2^32 -1 causes an overflow and results in 0.
        /// </summary>
        internal static string INC_Description {
            get {
                return ResourceManager.GetString("INC_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INC RXX.
        /// </summary>
        internal static string INC_Label {
            get {
                return ResourceManager.GetString("INC_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to performs a bitwise inversion of register Rxx.
        /// </summary>
        internal static string INV_Description {
            get {
                return ResourceManager.GetString("INV_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INV RXX.
        /// </summary>
        internal static string INV_Label {
            get {
                return ResourceManager.GetString("INV_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unconditionally jumps to instruction number d (1-based).
        /// </summary>
        internal static string JMP_Description {
            get {
                return ResourceManager.GetString("JMP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JMP d.
        /// </summary>
        internal static string JMP_Label {
            get {
                return ResourceManager.GetString("JMP_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jumps to instruction d (1-based) only if R00 contains 0.
        /// </summary>
        internal static string JZ_Description {
            get {
                return ResourceManager.GetString("JZ_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JZ d.
        /// </summary>
        internal static string JZ_Label {
            get {
                return ResourceManager.GetString("JZ_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copies the value from register Rxx to register Ryy.
        /// </summary>
        internal static string MOV_Description {
            get {
                return ResourceManager.GetString("MOV_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOV RXX,RYY.
        /// </summary>
        internal static string MOV_Label {
            get {
                return ResourceManager.GetString("MOV_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does nothing.
        /// </summary>
        internal static string NOP_Description {
            get {
                return ResourceManager.GetString("NOP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOP.
        /// </summary>
        internal static string NOP_Label {
            get {
                return ResourceManager.GetString("NOP_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copies the numeric constant d (specified as a decimal) to register Rxx.
        /// </summary>
        internal static string VMOV_Description {
            get {
                return ResourceManager.GetString("VMOV_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOV d,RXX.
        /// </summary>
        internal static string VMOV_Label {
            get {
                return ResourceManager.GetString("VMOV_Label", resourceCulture);
            }
        }
    }
}
